[project]
name = "dokku-blog-build"
version = "0.1.0"
description = "mkdocs build environment for the Dokku blog"
authors = [{ name = "Jose Diaz-Gonzalez", email = "email@josediazgonzalez.com" }]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
  "mkdocs>=1.6.1,<2",
  "mkdocs-material>=9.5.43,<10",
  "mkdocs-material-extensions>=1.3.1,<2",
  "mkdocs-exclude>=1.0.2,<2",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
