---
name: 'docs'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Setup python 3.10"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate documentation
        env:
          BOT_GITHUB_USERNAME: ${{ secrets.HOMEBREW_GITHUB_USERNAME }}
          BOT_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          echo "====> Authenticating to repository"
          git config --global user.name 'Dokku Bot'
          git config --global user.email no-reply@dokku.com

          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update -q
          sudo apt install gh -y -q

          gh auth login --with-token <<<"$BOT_GITHUB_API_TOKEN"

          echo "====> Fetching latest docs"
          rm -rf tmp
          git clone -q https://github.com/dokku/docs.git tmp

          echo "----> Generating docker image"
          make docs-build-image

          echo "----> Generating blog"
          make docs-build

          if [[ -n "$GITHUB_ACTION" ]]; then
            sudo chown -R "$(whoami)" blog
          fi

          rm -rf tmp/blog
          mv blog tmp/blog

          if [[ "$(git -C tmp ls-files -dmo)" == "blog/sitemap.xml.gz" ]]; then
            echo " !    No doc changes found"
            git -C tmp checkout -- blog/sitemap.xml.gz
          else
            echo "====> Pushing blog"
            git -C tmp add .
            git -C tmp commit -m "chore: regenerate blog"

            if [[ -n "$BOT_GITHUB_USERNAME" ]] && [[ -n "$BOT_GITHUB_API_TOKEN" ]]; then
              git -C tmp remote set-url origin "https://$BOT_GITHUB_USERNAME:$BOT_GITHUB_API_TOKEN@github.com/dokku/docs.git"
            fi

            git -C tmp push origin master
          fi
